### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'beautifulsoup4>=4.6.3' distribution was not found

### ISSUE THREAD

**Issue by trickeydan** [srobo/kitbook#8]
Looks like an issue with the dependency tree.

**Comment by keysmashes** [comment]
01a2ef0080feb9fa22ff29b8b53261bae76ab1aa removed bs4 from Pipfile.lock; i don't understand why.

getting pipenv to regenerate the lockfile resolves this error, but introduces more, because the dependencies aren't pinned, and e.g. mkdocs-material has bumped the major version and made breaking changes. pinning the dependencies in the Pipfile to the versions found in the runbook fixes those errors. i will submit a pr shortly.

this by the way is why i dislike pipenv. it clearly knows something's wrong! it'll even tell you... if you if you know to run `pipenv graph`... and scroll through a page of output... and see the one line with a single character that indicates that something's wrong:

```
mkdocs-mermaid-plugin==0.1.1
  - beautifulsoup4 [required: >=4.6.3, installed: ?]
```

even plain pip at least throws up a big warning if you've installed things without their dependencies.

**Comment by trickeydan** [comment]
> this by the way is why i dislike pipenv. 

You'll note that I don't use pipenv for projects now that better (and standardised!) tools are available. We should consider moving this project away from pipenv, although I'm hesitant about diverging too far from the runbook.
